"""add theme_mode to users

Revision ID: 840b18f132f9
Revises: be24c3672a69
Create Date: 2026-02-04 04:16:23.242621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840b18f132f9'
down_revision: Union[str, Sequence[str], None] = 'be24c3672a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme_mode')
    # ### end Alembic commands ###
